/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const OrderId = IDL.Text;
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const ListingId = IDL.Text;
export const Time = IDL.Int;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const CardRarity = IDL.Variant({
  'ultraRare' : IDL.Null,
  'rare' : IDL.Null,
  'holoRare' : IDL.Null,
  'secretRare' : IDL.Null,
  'common' : IDL.Null,
  'uncommon' : IDL.Null,
});
export const CardCondition = IDL.Variant({
  'damaged' : IDL.Null,
  'lightlyPlayed' : IDL.Null,
  'mint' : IDL.Null,
  'heavilyPlayed' : IDL.Null,
  'nearMint' : IDL.Null,
  'moderatelyPlayed' : IDL.Null,
});
export const Listing = IDL.Record({
  'id' : ListingId,
  'setName' : IDL.Text,
  'cardName' : IDL.Text,
  'createdAt' : Time,
  'description' : IDL.Text,
  'photoUrl' : ExternalBlob,
  'rarity' : CardRarity,
  'sellerId' : IDL.Principal,
  'price' : IDL.Nat,
  'condition' : CardCondition,
});
export const OrderStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
});
export const Order = IDL.Record({
  'id' : OrderId,
  'status' : OrderStatus,
  'platformFee' : IDL.Nat,
  'listingId' : ListingId,
  'createdAt' : Time,
  'buyerId' : IDL.Principal,
  'sellerId' : IDL.Principal,
  'stripeSessionId' : IDL.Text,
  'amount' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'completeOrder' : IDL.Func([OrderId], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createListing' : IDL.Func([Listing], [ListingId], []),
  'createOrder' : IDL.Func([ListingId, IDL.Text], [OrderId], []),
  'deleteListing' : IDL.Func([ListingId], [], []),
  'getAllListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getBuyerOrders' : IDL.Func([IDL.Principal], [IDL.Vec(Order)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getListing' : IDL.Func([ListingId], [Listing], ['query']),
  'getOrder' : IDL.Func([OrderId], [Order], ['query']),
  'getPlatformBalance' : IDL.Func([], [IDL.Nat], ['query']),
  'getSellerListings' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Listing)],
      ['query'],
    ),
  'getSellerOrders' : IDL.Func([IDL.Principal], [IDL.Vec(Order)], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchListings' : IDL.Func(
      [IDL.Text, IDL.Text, CardRarity, CardCondition],
      [IDL.Vec(Listing)],
      ['query'],
    ),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateListing' : IDL.Func([Listing], [Listing], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const OrderId = IDL.Text;
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const ListingId = IDL.Text;
  const Time = IDL.Int;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const CardRarity = IDL.Variant({
    'ultraRare' : IDL.Null,
    'rare' : IDL.Null,
    'holoRare' : IDL.Null,
    'secretRare' : IDL.Null,
    'common' : IDL.Null,
    'uncommon' : IDL.Null,
  });
  const CardCondition = IDL.Variant({
    'damaged' : IDL.Null,
    'lightlyPlayed' : IDL.Null,
    'mint' : IDL.Null,
    'heavilyPlayed' : IDL.Null,
    'nearMint' : IDL.Null,
    'moderatelyPlayed' : IDL.Null,
  });
  const Listing = IDL.Record({
    'id' : ListingId,
    'setName' : IDL.Text,
    'cardName' : IDL.Text,
    'createdAt' : Time,
    'description' : IDL.Text,
    'photoUrl' : ExternalBlob,
    'rarity' : CardRarity,
    'sellerId' : IDL.Principal,
    'price' : IDL.Nat,
    'condition' : CardCondition,
  });
  const OrderStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
  });
  const Order = IDL.Record({
    'id' : OrderId,
    'status' : OrderStatus,
    'platformFee' : IDL.Nat,
    'listingId' : ListingId,
    'createdAt' : Time,
    'buyerId' : IDL.Principal,
    'sellerId' : IDL.Principal,
    'stripeSessionId' : IDL.Text,
    'amount' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'completeOrder' : IDL.Func([OrderId], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createListing' : IDL.Func([Listing], [ListingId], []),
    'createOrder' : IDL.Func([ListingId, IDL.Text], [OrderId], []),
    'deleteListing' : IDL.Func([ListingId], [], []),
    'getAllListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getBuyerOrders' : IDL.Func([IDL.Principal], [IDL.Vec(Order)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getListing' : IDL.Func([ListingId], [Listing], ['query']),
    'getOrder' : IDL.Func([OrderId], [Order], ['query']),
    'getPlatformBalance' : IDL.Func([], [IDL.Nat], ['query']),
    'getSellerListings' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Listing)],
        ['query'],
      ),
    'getSellerOrders' : IDL.Func([IDL.Principal], [IDL.Vec(Order)], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchListings' : IDL.Func(
        [IDL.Text, IDL.Text, CardRarity, CardCondition],
        [IDL.Vec(Listing)],
        ['query'],
      ),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateListing' : IDL.Func([Listing], [Listing], []),
  });
};

export const init = ({ IDL }) => { return []; };