/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type CardCondition = { 'damaged' : null } |
  { 'lightlyPlayed' : null } |
  { 'mint' : null } |
  { 'heavilyPlayed' : null } |
  { 'nearMint' : null } |
  { 'moderatelyPlayed' : null };
export type CardRarity = { 'ultraRare' : null } |
  { 'rare' : null } |
  { 'holoRare' : null } |
  { 'secretRare' : null } |
  { 'common' : null } |
  { 'uncommon' : null };
export type ExternalBlob = Uint8Array;
export interface Listing {
  'id' : ListingId,
  'setName' : string,
  'cardName' : string,
  'createdAt' : Time,
  'description' : string,
  'photoUrl' : ExternalBlob,
  'rarity' : CardRarity,
  'sellerId' : Principal,
  'price' : bigint,
  'condition' : CardCondition,
}
export type ListingId = string;
export interface Order {
  'id' : OrderId,
  'status' : OrderStatus,
  'platformFee' : bigint,
  'listingId' : ListingId,
  'createdAt' : Time,
  'buyerId' : Principal,
  'sellerId' : Principal,
  'stripeSessionId' : string,
  'amount' : bigint,
}
export type OrderId = string;
export type OrderStatus = { 'pending' : null } |
  { 'completed' : null };
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'completeOrder' : ActorMethod<[OrderId], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  /**
   * / Returns newly created listing id
   */
  'createListing' : ActorMethod<[Listing], ListingId>,
  'createOrder' : ActorMethod<[ListingId, string], OrderId>,
  'deleteListing' : ActorMethod<[ListingId], undefined>,
  'getAllListings' : ActorMethod<[], Array<Listing>>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getBuyerOrders' : ActorMethod<[Principal], Array<Order>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getListing' : ActorMethod<[ListingId], Listing>,
  'getOrder' : ActorMethod<[OrderId], Order>,
  'getPlatformBalance' : ActorMethod<[], bigint>,
  'getSellerListings' : ActorMethod<[Principal], Array<Listing>>,
  'getSellerOrders' : ActorMethod<[Principal], Array<Order>>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchListings' : ActorMethod<
    [string, string, CardRarity, CardCondition],
    Array<Listing>
  >,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  /**
   * / Returns the existing listing
   */
  'updateListing' : ActorMethod<[Listing], Listing>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];